### ISSUE TITLE
Gradient on edge

### ISSUE THREAD

**Issue by TagLoomis** [webgeodatavore/GeoJSON.Terminator#1]
This is a great piece of code.

I'm wondering if it's possible to add a gradient/faded/ soft edge to the outline?

**Comment by ThomasG77** [comment]
> I'm wondering if it's possible to add a gradient/faded/ soft edge to the outline?
It's not in any roadmap on my side as it's more or less a port of Leaflet version that does not support this feature. You can always submit a PR if you really need it.

The current library was an attempt due to https://github.com/openlayers/openlayers/issues/8570
You may find some clue for what you want e.g "gradient/faded/ soft edge" in the discussion from this same issue, in particular the last message.
